/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import DAO.*;
import entities.*;


/**
 *
 * @author Carlos
 */
public class Acceil extends javax.swing.JFrame {

    /**
     * Creates new form Acceil
     */
    public Acceil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfexprim = new javax.swing.JTextField();
        labelpub = new javax.swing.JLabel();
        btpublier = new javax.swing.JButton();
        btjaim = new javax.swing.JButton();
        btcomment = new javax.swing.JButton();
        tfcomment = new javax.swing.JTextField();
        labelpub2 = new javax.swing.JLabel();
        btjaim2 = new javax.swing.JButton();
        tfcomment2 = new javax.swing.JTextField();
        btcomment2 = new javax.swing.JButton();
        labelcomment = new javax.swing.JLabel();
        labellike = new javax.swing.JLabel();
        labellike2 = new javax.swing.JLabel();
        labelcomment2 = new javax.swing.JLabel();
        btafficher = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bonjour Mr");

        jLabel2.setText("chercher");

        jButton1.setText("Acceil");

        jButton2.setText("Profil");

        jButton3.setText("Reseau");

        jButton4.setText("Messages");

        jButton5.setText("Centre d'interet");

        jButton6.setText("Mes publications");

        jButton7.setText("essayer compte premium");

        jLabel3.setText("exprimez vous..");

        tfexprim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfexprimActionPerformed(evt);
            }
        });

        labelpub.setText("publication");

        btpublier.setText("publier");
        btpublier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpublierActionPerformed(evt);
            }
        });

        btjaim.setText("j'aime");
        btjaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btjaimActionPerformed(evt);
            }
        });

        btcomment.setText("commenter");
        btcomment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcommentActionPerformed(evt);
            }
        });

        labelpub2.setText("publication");

        btjaim2.setText("j'aime");
        btjaim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btjaim2ActionPerformed(evt);
            }
        });

        tfcomment2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcomment2ActionPerformed(evt);
            }
        });

        btcomment2.setText("commenter");
        btcomment2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcomment2ActionPerformed(evt);
            }
        });

        labelcomment.setText("votre commentaire");

        labelcomment2.setText("votre commentaire");

        btafficher.setText("afficher publication");
        btafficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btafficherActionPerformed(evt);
            }
        });

        jButton8.setText("Notifications");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(41, 41, 41)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btjaim2)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfcomment2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btcomment2))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(labelpub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                                .addComponent(tfexprim, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(18, 18, 18)
                                            .addComponent(btpublier))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton3)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton4)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton5)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton6)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton7))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(labellike, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(154, 154, 154)
                            .addComponent(labellike2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(labelcomment2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(286, 286, 286))))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelcomment, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelpub2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btjaim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfcomment, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btcomment))
                            .addComponent(btafficher))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfexprim, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btpublier))
                .addGap(47, 47, 47)
                .addComponent(labelpub, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelcomment, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labellike, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfcomment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btcomment))
                    .addComponent(btjaim))
                .addGap(18, 18, 18)
                .addComponent(btafficher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelpub2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labellike2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelcomment2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcomment2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcomment2)
                    .addComponent(btjaim2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfexprimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfexprimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfexprimActionPerformed

    private void btpublierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpublierActionPerformed
        publication p = new publication();
        membre m = new membre();
        
        p.setContenu(tfexprim.getText());
        
        membreDAO mdao = new membreDAO();
        
        mdao.addPub(m, p);
        
        String pub = tfexprim.getText();
        labelpub.setText(pub);
        
        
        
        
    
    }//GEN-LAST:event_btpublierActionPerformed

    private void btcommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcommentActionPerformed
        commentaire c = new commentaire();
        publication p = new publication();
        membre m = new membre();
        
        
       c.setContenuC(tfcomment.getText());
       p.setContenu(labelpub.getText());
      
       commentaireDAO cdao = new commentaireDAO();
       membreDAO mdao = new membreDAO();
       publicationDAO pdao = new publicationDAO();
       
       mdao.ajouterCommentaire(m, c);
       
       String comment = tfcomment.getText();
       labelcomment.setText(comment);
       
       
    }//GEN-LAST:event_btcommentActionPerformed

    private void btjaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btjaimActionPerformed
        //String likeornot = btjaim.getName();
        //if(likeornot == "j'aime'" )
        String msg = "vous aimer ça";
        String verif = labellike.getText();
        if(msg != verif)
        {labellike.setText(msg);}
        else {
            msg="";
            labellike.setText(msg);
        }   
    }//GEN-LAST:event_btjaimActionPerformed

    private void btjaim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btjaim2ActionPerformed
        String msg = "vous aimer ça";
        String verif = labellike2.getText();
        if(msg != verif)
        {labellike2.setText(msg);}
        else {
            msg="";
            labellike2.setText(msg);
        }
    }//GEN-LAST:event_btjaim2ActionPerformed

    private void tfcomment2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcomment2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcomment2ActionPerformed

    private void btcomment2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcomment2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcomment2ActionPerformed

    private void btafficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btafficherActionPerformed
        
        publication p = new publication();
        
        
        
    }//GEN-LAST:event_btafficherActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceil().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btafficher;
    private javax.swing.JButton btcomment;
    private javax.swing.JButton btcomment2;
    private javax.swing.JButton btjaim;
    private javax.swing.JButton btjaim2;
    private javax.swing.JButton btpublier;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelcomment;
    private javax.swing.JLabel labelcomment2;
    private javax.swing.JLabel labellike;
    private javax.swing.JLabel labellike2;
    private javax.swing.JLabel labelpub;
    private javax.swing.JLabel labelpub2;
    private javax.swing.JTextField tfcomment;
    private javax.swing.JTextField tfcomment2;
    private javax.swing.JTextField tfexprim;
    // End of variables declaration//GEN-END:variables
}
