/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.membreDAO;
//import static GUI.ProfilFrameRem.idmemberinscri;
import entities.membre;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**w
 *
 * @author user
 */
public class RegisterFrame extends javax.swing.JFrame {
 public static int idmemberinscri;
 membre m1=null;
 membreDAO mdao=new membreDAO();
 public static String s=null;
    /**
     * Creates new form RegisterFrame
     */
    boolean x;
    public  boolean isValidEmailAddress(String email) {
           String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
    }
    public RegisterFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(400, 500);
        this.setTitle("JOBSEEKERS");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        image.addActionListener(new ActionListener(){
      
     @Override
     public void actionPerformed(ActionEvent e){
         JFileChooser fileChooser = new JFileChooser();
         fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
         fileChooser.addChoosableFileFilter(filter);
         int result = fileChooser.showSaveDialog(null);
         if(result == JFileChooser.APPROVE_OPTION){
             File selectedFile = fileChooser.getSelectedFile();
             String path = selectedFile.getAbsolutePath();
             
             label.setIcon(ResizeImage(path));
             s = path;
             System.out.println(path);
              }
         else if(result == JFileChooser.CANCEL_OPTION){
             System.out.println("No Data");
         }
     }});
    }

        public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(label.getWidth(), label.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
        
        
        
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtcin = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        cmdp = new javax.swing.JPasswordField();
        image = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        txtpays = new javax.swing.JComboBox<>();
        txtmdp = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 700));
        setMinimumSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("Inscription");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 0, 180, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 70, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("iinserer image");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 440, 100, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Prenom");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 160, 48, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Date naissance");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 200, 100, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Sexe");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 280, 50, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Pays");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 240, 34, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 320, 34, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("mot de passe");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 400, 100, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("s'inscrire");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 530, 130, 50);
        getContentPane().add(txtcin);
        txtcin.setBounds(130, 60, 130, 30);
        getContentPane().add(txtprenom);
        txtprenom.setBounds(130, 150, 130, 30);
        getContentPane().add(txtemail);
        txtemail.setBounds(130, 310, 130, 30);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Homme");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(120, 270, 90, 30);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("Femme");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(210, 270, 90, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lg.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 0, 50, 50);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 10, 0, 0);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nom");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 120, 70, 20);
        getContentPane().add(txtnom);
        txtnom.setBounds(130, 110, 130, 30);

        cmdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdpActionPerformed(evt);
            }
        });
        getContentPane().add(cmdp);
        cmdp.setBounds(130, 390, 130, 30);

        image.setText("Browse");
        image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageActionPerformed(evt);
            }
        });
        getContentPane().add(image);
        image.setBounds(190, 440, 75, 25);

        label.setText("Label");
        getContentPane().add(label);
        label.setBounds(380, 50, 100, 130);

        txtpays.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afrique du Sud", "Algérie", "Angola", "Bénin", "Botswana", "Burkina Faso", "Burundi", "Cameroun", "Cap-Vert", "République centrafricaine", "Comores", "République du Congo", "République démocratique du Congo", "Côte d’Ivoire", "Djibouti", "Égypte", "Érythrée", "Éthiopie", "Gabon", "Gambie", "Ghana", "Guinée", "Guinée-Bissau", "Guinée équatoriale", "Kenya", "Lesotho", "Liberia", "Libye", "Madagascar", "Malawi", "Mali", "Maroc", "Maurice", "Mauritanie", "Mozambique", "Namibie", "Niger", "Nigeria", "Ouganda", "Rwanda", "Sahara Occidental", "Sao Tomé-et-Principe", "Sénégal", "Seychelles", "Sierra Leone", "Somalie", "Soudan", "Soudan du Sud", "Swaziland", "Tanzanie", "Tchad", "Togo", "Tunisie", "Zambie", "Zimbabwe", "Antigua-et-Barbuda", "Argentine", "Bahamas", "Barbade", "Belize", "Bolivie", "Brésil", "Canada", "Chili", "Colombie", "Costa Rica", "Cuba", "République dominicaine", "Dominique", "Équateur", "États-Unis", "Grenade", "Guatemala", "Guyana", "Haïti", "Honduras", "Jamaïque", "Mexique", "Nicaragua", "Panama", "Paraguay", "Pérou", "Saint-Christophe-et-Niévès", "Sainte-Lucie", "Saint-Vincent-et-les-Grenadines", "Salvador", "Suriname", "Trinité-et-Tobago", "Uruguay", "Venezuela", "Afghanistan", "Arabie saoudite", "Arménie", "Azerbaïdjan", "Bahreïn", "Bangladesh", "Bhoutan", "Birmanie", "Brunei", "Cambodge", "Chine", "Chypre", "Corée du Nord", "Corée du Sud", "Émirats arabes unis", "Géorgie", "Inde", "Indonésie", "Irak", "Iran", "Israël", "Japon", "Jordanie", "Kazakhstan", "Kirghizistan", "Koweït", "Laos", "Liban", "Malaisie", "Maldives", "Mongolie", "Népal", "Oman", "Ouzbékistan", "Pakistan", "Philippines", "Qatar", "Singapour", "Sri Lanka", "Syrie", "Tadjikistan", "Thaïlande", "Timor oriental", "Turkménistan", "Turquie", "Viêt Nam", "Yémen", "Albanie", "Allemagne", "Andorre", "Autriche", "Belgique", "Biélorussie", "Bosnie-Herzégovine", "Bulgarie", "Chypre", "Crete", "Croatie", "Danemark", "Espagne", "Estonie", "Finlande", "France", "Grèce", "Hongrie", "Irlande", "Islande", "Italie", "Lettonie", "Liechtenstein", "Lituanie", "Luxembourg", "Macédoine", "Malte", "Moldavie", "Monaco", "Monténégro", "Norvège", "Pays-Bas", "Pologne", "Portugal", "République tchèque", "Roumanie", "Royaume-Uni", "Russie", "Saint-Marin", "Serbie", "Slovaquie", "Slovénie", "Suède", "Suisse", "Ukraine", "Vatican", "Australie", "Fidji", "Kiribati", "Marshall", "Micronésie", "Nauru", "Nouvelle-Zélande", "Palaos", "Papouasie-Nouvelle-Guinée", "Salomon", "Samoa", "Tonga", "Tuvalu", "Vanuatu" }));
        getContentPane().add(txtpays);
        txtpays.setBounds(130, 230, 130, 30);
        getContentPane().add(txtmdp);
        txtmdp.setBounds(130, 350, 130, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Mot de passe");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 350, 100, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Confirm ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 380, 100, 20);

        txtdate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txtdate);
        txtdate.setBounds(130, 192, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        membre m = new membre();
        int k=Integer.parseInt(txtcin.getText());
       
         m.setCin(k);
     if(txtcin.getText().equals(""))
     {
         JOptionPane.showMessageDialog(null,"saisir votre cin") ;
     }
     m.setNom(txtnom.getText());
     if(txtnom.getText().equals(""))
     {
         JOptionPane.showMessageDialog(null,"saisir votre nom") ;
     }
     m.setPrenom(txtprenom.getText());
     if(txtprenom.getText().equals(""))
     {
         JOptionPane.showMessageDialog(null,"saisir votre prénom") ;
     }
      String k2=(((JTextField)txtdate.getDateEditor().getUiComponent()).getText());
     m.setAge(k2);
     //if(txtdate.getText().equals(""))
    /* {
         JOptionPane.showMessageDialog(null,"saisir votre date de naissance") ;
     }*/
     m.setPays(txtpays.getSelectedItem().toString());      
     if(jRadioButton1.isSelected())
     { 
         m.setSexe(jRadioButton1.getText());
     } else if(jRadioButton2.isSelected())
     { m.setSexe(jRadioButton2.getText());}
     else 
         JOptionPane.showMessageDialog(null,"verifier votre sexe") ;
     
     
     
     
     
        
        x=isValidEmailAddress(txtemail.getText());
        System.out.println(x);
        if (x=false)  
             JOptionPane.showMessageDialog(null, "email invalide");
         else 
             m.setMail(txtemail.getText());
         
     
    
     
     if(txtmdp.getText().equals(""))
     {
         JOptionPane.showMessageDialog(null,"saisir votre mot de passe") ;
     }
     //m.setPwd(cmdp.getText());
      if(txtmdp.getText().equals(cmdp.getText()))
     {
        m.setPwd(txtmdp.getText()); 
     }
      else
      JOptionPane.showMessageDialog(null,"mot de passe non identique") ;
        System.out.println(cmdp.getText()+"   "+txtmdp.getText());
      
     membreDAO dao = new membreDAO();
     dao.add(m);
     
     
     
     
     String mail =txtemail.getText();
        
        m1 = mdao.findObjectByMail(mail);
        
       
        idmemberinscri=m1.getId_membre();
        System.out.println(idmemberinscri);
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"remplir tous les champs") ;
                }
        
     ProfilFrameRem pof= new ProfilFrameRem();
        pof.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_imageActionPerformed

    private void cmdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdpActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cmdp;
    private javax.swing.JButton image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel label;
    private javax.swing.JTextField txtcin;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtmdp;
    private javax.swing.JTextField txtnom;
    private javax.swing.JComboBox<String> txtpays;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
}
